inherit_from: .rubocop_todo.yml

require: rubocop-rspec

Rails:
  Enabled: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'config/deploy/**/*'
    - 'features/**/*'

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/author/submissions_controller.rb'
    - 'app/controllers/ldap_lookup_controller.rb'
    - 'app/models/author.rb'
    - 'app/models/ldap_result.rb'
    - 'app/controllers/admin/submissions_controller.rb'
    - 'app/controllers/catalog_controller.rb'
    - 'app/models/legacy/main_submission.rb'
    - 'app/models/submission.rb'
    - 'app/presenters/admin/submissions_dashboard_view.rb'
    - 'app/presenters/admin/submissions_index_view.rb'
    - 'app/presenters/submission_view.rb'
    - 'app/models/ldap_university_directory.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/models/legacy/main_submission.rb'
    - 'app/presenters/admin/submission_form_view.rb'
    - 'app/presenters/admin/submissions_index_view.rb'
    - 'app/models/ldap_university_directory.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/models/legacy/main_submission.rb'
    - 'app/presenters/admin/submission_form_view.rb'
    - 'app/presenters/admin/submissions_index_view.rb'
    - 'app/models/ldap_university_directory.rb'

Layout/MultilineBlockLayout:
  Exclude:

Layout/IndentationConsistency:
  EnforcedStyle: rails

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/WordArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/ClassVars:
  Exclude:
    - 'spec/support/authentication.rb'

Naming/VariableName:
  Exclude:
    - 'lib/share_notify/push_document.rb'

Style/BracesAroundHashParameters:
  Exclude:
    - 'config/deploy.rb'
    - 'spec/component/models/solr_data_import_service_spec.rb'

Layout/SpaceInsideBlockBraces:
  Exclude:
    - 'spec/component/models/solr_data_import_service_spec.rb'

Layout/SpaceInsideHashLiteralBraces:
  Exclude:
    - 'spec/component/models/solr_data_import_service_spec.rb'

Naming/AccessorMethodName:
  Exclude:

Naming/PredicateName:
  Exclude:

Lint/HandleExceptions:
  Exclude:

Rails/Date:
  Enabled: false

Rails/Output:
  Exclude:

Rails/TimeZone:
  Enabled: false

RSpec/ExampleWording:
  CustomTransform:
    be: is
    have: has
    not: does not
    NOT: does NOT
  IgnoredWords:
    - only

RSpec/FilePath:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/DescribeClass:
  Exclude:



RSpec/MultipleDescribes:
  Enabled: false

Style/BlockDelimiters:
  Exclude:

Naming/FileName:
  Exclude:
