language: ruby
cache: bundler
sudo: required
#rvm:
#- 2.4.3
jdk:
- oraclejdk8
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - JS=true
before_install:
  - "gem --version"
  - "gem update --system"
  - "gem --version"
  - "gem install bundler"
  - "gem update bundler"
script:
- gem install bundler
- gem install rspec
- bundle exec rubocop
- bundle exec rspec 
notifications:
  email:
    recipients:
    - amg32@psu.edu, ajk5603@psu.edu
    on_success: change
    on_failure: always
  irc:
    channels: 
    template: 



