sudo: false
language: ruby
rvm:
  - 2.4.1
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install: gem install bundler -v 1.16.0.pre.2
script:
- bundle exec rubocop
- bundle exec rspec 
notifications:
  email:
    recipients:
    - jxb13@psu.edu
    on_success: change
    on_failure: always
  irc:
    channels: 
    template: 
