language: ruby
cache: bundler
sudo: required
#rvm:
#- 2.4.3
jdk:
- oraclejdk8
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - JS=truesudo: false
script:
- gem install bundler
- gem install rspec
- bundle exec rubocop
- bundle exec rspec 
notifications:
  email:
    recipients:
    - jxb13@psu.edu
    on_success: change
    on_failure: always
  irc:
    channels: 
    template: 



